# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Read and print the working directory
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls -la
      pwd

# Cache task
- task: Cache@2
  displayName: Cache
  inputs:
    key: 'npm | "$(Agent.OS)" | $(System.DefaultWorkingDirectory)/package.json'
    path: '$(System.DefaultWorkingDirectory)/node_modules'

# Deletes node_modules, helps catch errors

- script: npm ci